### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by tremblap**

### CODE REVIEW

**Comment by tremblap** [comment]
a proposed template for bug and unexpected behaviour

**Review by weefuzzy — APPROVED** [review]
Looks fine to get going with. Thanks.

**Comment by jamesb93** [comment]
I would use the forms feature to make this simpler and more readable.

**Review by jamesb93 — APPROVED** [review]

**Comment by weefuzzy** [comment]
Thanks for that, but I think we've lost useful flexibility because now there is nowhere for people to include code snippets (or attachments?), which I think is to be encouraged, welcomed, cherished etc. Personally I'm satisfied with something that encourages useful reports but stops short of trying to mandate exactly what they should look like (it's not like we're dealing with thousands)

**Comment by tremblap** [comment]
@weefuzzy the box allows drag and drop, is that ok or do you have another preferred format than this?

**Comment by weefuzzy** [comment]
Yeah, all good. @jamesb93 explained how computers work for me, and has graciously emboldened the text about drag n' drop for the hard of understanding.

**Pull request merged**
