### PR TITLE
fixes #256 - checking input to env with filters

### LINKED ISSUE #256: `fluid.ampfeature~` can break when it receives a `nan`
As outlined in [this thread](https://discourse.flucoma.org/t/fluid-ampfeature-stops-working-sometimes/) on the discourse when `fluid.ampfeature~` receives a `nan` its own output breaks.

### What was the expected result?

The envelope follower should get pulled in that direction but not ultimately fail.

### What was the actual result?

The object stops working until audio is restarted.

### What operating system were you using?

Mac

### Operating system version

macOS 13.4.1

### FluCoMa Version

1.0.6

### PR DESCRIPTION
**Pull request by tremblap**
check the input to env and envgate and stores the last valid value to replace non-finite values with

### CODE REVIEW

**Comment by AlexHarker** [comment]
See my last comment on the issue. I think there's a better solution.

**Review by weefuzzy — CHANGES_REQUESTED** [review]
Logically looks fine. I have only stylistic consistency nitpicks, at least one of which should have been caught by clang-format: 

* We've been using newline before braces everywhere, IIRC. clang-format should be doing this. 
* Prefer brace-initialization  of the member variable if that's how all the others are done
* Maybe this has just passed the threshold of fiddly-ness where the code duplication between `Envelope.hpp` and `EnvelopeGate.hpp` is tiresome. Could think about pulling out the whole `test if finite and filter-twice-if-needed` saga into its own thing

**Comment by tremblap** [comment]
I have satisfied @weefuzzy first 2 demands. clang-format revealed other discrepancies which I've pushed as we may as well clean it here. As much as I agree with the spirit of the 3rd request, I'd do a proper refactor of these 2 things to make them more efficient in block process (they are doing sample per sample now which is suboptimal)

**Comment by weefuzzy** [comment]
> (they are doing sample per sample now which is suboptimal)

Don't think there's a way around that for these algorithms because they need per-sample feedback. 

But, in any case, is was the formatting consistency that was the thing here. I'd be inclined to go with this unless there's a clear functional reason to play with the other solution ahead of just fixing this bug. Feels to me like a we-can-revisit-if-it's-a-problem kind of thing.

**Review by weefuzzy — APPROVED** [review]

**Comment by tremblap** [comment]
ok thanks both. Let's put that fix in and consider other options as future improvements

**Pull request merged**
