### PR TITLE
Test/sc ports/slicers

### PR DESCRIPTION
**Pull request by weefuzzy**
Ports of the SC unit tests for slicers. These bypass the clients and work on the algorithms directly, so there's less stuff in the way. 

Includes useful plumbing for loading audio data for tests

### CODE REVIEW

**Comment by tremblap** [comment]
I'm not sure what I have to do here except the new novelty mfcc values for the SC and C++ UTs, right?

**Comment by weefuzzy** [comment]
Right. That shouldn't affect this PR. 

I need to find out why some tests are timing out on Windows, but that's unconnected :shrug:

**Comment by weefuzzy** [comment]
Faulty tests fixed. I'd be inclined to merge this in now, seeing as the CI has run the tests themselves and now pronounces that all is well

**Review by tremblap — APPROVED** [review]
it worked for me locally - I haven't check performance of code but that is not part of the quesiton iiuc so go for it if you are happy with the windows fix

**Pull request merged**
