### PR TITLE
Appropriate client methods are now const

### PR DESCRIPTION
**Pull request by AlexHarker**
This is desirable as it allows differentiation outside of the client / parameter set of what will touch object state (which applying constraints does not).

This will aid in reasoning about threading things in other places.

### CODE REVIEW

**Review by weefuzzy — APPROVED** [review]
Seems cromulent, thanks.

**Comment by AlexHarker** [comment]
Thanks @weefuzzy - are you happy with the further additions before I merge? The most salient one is the enable_if_t refactor (I couldn't get the method const any other way). This was suggested by @lewardo as an alternative incantation, but I cannot say I ever really feel I understand the details of std::enable_if_t

**Comment by weefuzzy** [comment]
Should be equivalent 😬 I think the difference is in the context in which the method is enabled / disabled, so that in the first case it was too 'late' to be consty. Or something.

**Comment by AlexHarker** [comment]
@tremblap - these changes are pretty minimal (there are a lot, but they shouldn't do anything and if they did the compiler should test them) but given the number can you give them a spin in your preferred methods before merging?

**Pull request merged**
