### PR TITLE
NMFClient: Add resynth mode to de-magic interface

### PR DESCRIPTION
**Pull request by weefuzzy**
In anticipation of the buffer management PR, this changes the interface of NMF to add a `resynthMode` signalling whether or not resynthesis should occur. Whilst it introduces verbosity, it reduces the amount of magic in the object. 

Also now allow resynth from fixed bases + activations (which, e.g., allows post processing analysis results and then resynthesizing components). 

Finally, diagnostic messages are updated to use the same terminology as the interface. 

There will be an accompanying PR for SC

### CODE REVIEW

**Comment by jamesb93** [comment]
I didn't fully realise how cool this could be with the new resynth options! Testing coming...

**Comment by jamesb93** [comment]
First thing I've noticed is that the default `resynthMode` is not the old behaviour. My is that it's going to get frustrating constantly changing that attribute when the common usage is to get some resynth from a source buffer given some components.

**Comment by weefuzzy** [comment]
Don't know how you could recreate the old behaviour. Either it's different when the resynth buffer is present and the flag is 0, or it's different when it isn't present and the flag is 1.

**Comment by jamesb93** [comment]
> Also now allow resynth from fixed bases + activations (which, e.g., allows post processing analysis results and then resynthesizing components).

I was experimenting with something like this. It's not particularly useful (though I anticipate some more refined patching might lead somewhere) but it proves that it works.

image

**Comment by jamesb93** [comment]
> Don't know how you could recreate the old behaviour. Either it's different when the resynth buffer is present and the flag is 0, or it's different when it isn't present and the flag is 1.

I guess I just misunderstand the attribute then.

**Comment by weefuzzy** [comment]
> I guess I just misunderstand the attribute then.

It means 'should I try and resynthesize' (at which point the `resynth` buffer will actually be checked to see if anything is assigned, and whether it's actually a buffer etc)

**Comment by jamesb93** [comment]
> 

In that case, is it not the case that the default behaviour was mode 1?

**Comment by weefuzzy** [comment]
No, because it depended on whether `resynth` was assigned. If it was, then this is the equivalent of `resynthMode 1` but otherwise, it would be the equivalent of `resynthMode 0`. There's no way of perfectly replicating that now. The issue being that, with the buffer managment PR, if `resynth` isn't assigned by the user, it will be assigned by the the wrapper so we need some way of being able to not resynthesise. 

i.e. 
`[fluid.bufnmf~ @bases bar @activations foobar]` used to implicitly mean don't resynthesize. But now (with the PR), `@resynth` would be internally given a managed `buffer~` `u127373744` or whatever, so would unconditionally resynthesise.

**Comment by jamesb93** [comment]
> if `resynth` isn't assigned by the user, it will be assigned by the the wrapper so we need some way of being able to not resynthesise.

Right! This makes sense to me now.

**Pull request merged**
