### PR TITLE
EnvelopeGate: Address performance by avoiding (so much) copying

### LINKED ISSUE #22: fluid.ampgate~ cpu usagewith with `minlength` attributes
via https://discourse.flucoma.org/t/fluid-ampgate-cpu-usage/949

Reports of CPU hitting 90-100 % with the `minlength` attributes set in the order of 100 - 1000 ms. Will profile...

### PR DESCRIPTION
**Pull request by weefuzzy**
resolves #22 

Checked in SC and Max. SC tests pass. 

In the interests of simplicity in already complex code, the current implementation updates its input and output buffers by block copying the old buffer content to its new positions. This introduces a great deal of overhead, which grows markedly as `minLengthAbove` / `minLengthBelow` get bigger, and pegs out at 100% CPU for reasonable-seeming values. 

Rather than copying the data around, here I instead do the conventional ring buffer thing of moving read / write heads through the buffers. The downside, obviously, is that operations that were previously on contiguous ranges now sometimes have to be split into two operations, where the range crosses the edges of the buffer. This adds complexity / decreases clarity. On the upside, it means that performance no longer degrades steeply when using these attributes. 

I've done everything inline here in the name of applying the minimal changes needed to fix the problem and pass tests. However, happy to go off and consider if there's a way of hiding some of this complexity away so that the intention of the algorithm code can remain clear(er). The three main horrible bits are `refineStart` (where the search for the next minimum may have to be spread over two separate reads of the input buffer), and the two blocks in `processSample` that set ranges of the outputBuffer.

### CODE REVIEW

**Comment by tremblap** [comment]
Example code below goes from 65% to 0.6% in SC, nice one!

b = Buffer.read(s,File.realpath(FluidAmpGate.class.filenameSymbol).dirname.withTrailingSlash ++ "../AudioFiles/Nicol-LoopE-M.wav");

(
{var env, source = PlayBuf.ar(1,b,loop: 1);
    env = FluidAmpGate.ar(source, rampUp:441, rampDown:2205, onThreshold:-27, offThreshold: -31, minSilenceLength:4410, lookBack:441, highPassFreq:20, lookAhead: 22050);
    DelayN.ar(source,delaytime:22050/44100)*env;
}.play;
)

**Comment by tremblap** [comment]
I would merge now, but I have sent a compiled version to the bug reporter to see if it works for him.

**Comment by tremblap** [comment]
As I was playing with it, I have found a crash:

> Process:               Max [13832]
Path:                  /Applications/Max.app/Contents/MacOS/Max
Identifier:            com.cycling74.Max
Version:               8.1.11 [17de540] (8.1.11)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Max [13832]
User ID:               504

Date/Time:             2021-08-24 10:05:37.843 -0400
OS Version:            Mac OS X 10.15.7 (19H1323)
Report Version:        12
Bridge OS Version:     5.5 (18P4759a)
Anonymous UUID:        5D2CB51D-2D55-1359-9253-752F9C7BCF74

Sleep/Wake UUID:       16B6A978-4D87-4036-A1F9-CE12632FD321

Time Awake Since Boot: 32000 seconds
Time Since Wake:       3700 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called
Max(13832,0x108fbadc0) malloc: *** error for object 0xc02a000000000000: pointer being freed was not allocated
 

Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff6deaa33a __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff6df66e60 pthread_kill + 430
2   libsystem_c.dylib             	0x00007fff6de31808 abort + 120
3   libsystem_malloc.dylib        	0x00007fff6df2750b malloc_vreport + 548
4   libsystem_malloc.dylib        	0x00007fff6df2a40f malloc_report + 151
5   org.flucoma.fluid.ampgate-    	0x0000000141233594 fluid::client::FluidMaxWrapper<fluid::client::ClientWrapper<fluid::client::ampgate::AmpGateClient> >::~FluidMaxWrapper() + 52
6   com.cycling74.Max             	0x000000010472faa9 freeobject + 108
7   com.cycling74.Max             	0x00000001048cceac jnewobj_free + 26
8   com.cycling74.Max             	0x000000010472faa9 freeobject + 108
9   com.cycling74.Max             	0x00000001047fe674 object_free + 27
10  com.cycling74.Max             	0x00000001048de8b2 jpatcher_free + 326
11  com.cycling74.Max             	0x000000010472faa9 freeobject + 108
12  com.cycling74.Max             	0x00000001048cceac jnewobj_free + 26
13  com.cycling74.Max             	0x000000010472faa9 freeobject + 108
14  com.cycling74.Max             	0x00000001047fe674 object_free + 27
15  com.cycling74.Max             	0x00000001048de8b2 jpatcher_free + 326
16  com.cycling74.Max             	0x000000010472faa9 freeobject + 108
17  com.cycling74.Max             	0x00000001047fe674 object_free + 27
18  com.cycling74.Max             	0x00000001047fddcb object_method_imp + 340
19  com.cycling74.Max             	0x00000001049120f4 jwind_close + 1122
20  com.cycling74.Max             	0x0000000104800b6d object_method_typedfun + 75
21  com.cycling74.Max             	0x00000001048c78df jmenuitem_process + 553
22  com.cycling74.Max             	0x00000001048c76a8 jmenu_command_process + 71
23  com.cycling74.Max             	0x00000001048c764a jmenu_process + 99
24  com.cycling74.Max             	0x000000010482ce24 interface_process + 11
25  com.cycling74.Max             	0x0000000104f58ea0 juce::MessageManager::AsyncCallInvoker<juce::JuceMainMenuHandler::invoke(juce::PopupMenu::Item const&, int) const::'lambda'()>::messageCallback() + 96
26  com.cycling74.Max             	0x0000000104e49312 juce::MessageQueue::runLoopSourceCallback(void*) + 242
27  com.apple.CoreFoundation      	0x00007fff33ca27e2 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
28  com.apple.CoreFoundation      	0x00007fff33ca2781 __CFRunLoopDoSource0 + 103
29  com.apple.CoreFoundation      	0x00007fff33ca259b __CFRunLoopDoSources0 + 209
30  com.apple.CoreFoundation      	0x00007fff33ca12ca __CFRunLoopRun + 927
31  com.apple.CoreFoundation      	0x00007fff33ca08ce CFRunLoopRunSpecific + 462
32  com.apple.HIToolbox           	0x00007fff328ccabd RunCurrentEventLoopInMode + 292
33  com.apple.HIToolbox           	0x00007fff328cc6f4 ReceiveNextEventCommon + 359
34  com.apple.HIToolbox           	0x00007fff328cc579 _BlockUntilNextEventMatchingListInModeWithFilter + 64
35  com.apple.AppKit              	0x00007fff30f13739 _DPSNextEvent + 883
36  com.apple.AppKit              	0x00007fff30f11f80 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
37  com.apple.AppKit              	0x00007fff30f03c8e -[NSApplication run] + 658
38  org.chromium.ContentShell.framework	0x000000010c0faa0c cef_time_delta + 2877996
39  org.chromium.ContentShell.framework	0x000000010c0f97d3 cef_time_delta + 2873331
40  org.chromium.ContentShell.framework	0x000000010c0b6f7a cef_time_delta + 2600858
41  org.chromium.ContentShell.framework	0x000000010c088f1e cef_time_delta + 2412350
42  org.chromium.ContentShell.framework	0x000000010bdb5d33 ChromeAppModeStart_v6 + 6537459
43  com.cycling74.Max             	0x0000000104a71b0e MaxCefEventLoopHandler::runMessageLoop() + 18
44  com.cycling74.Max             	0x0000000104e4a3b5 juce::JUCEApplicationBase::main(int, char const**) + 245
45  libdyld.dylib                 	0x00007fff6dd62cc9 start + 1

**Comment by AlexHarker** [comment]
I just took a quick look at this with PA and I'm wondering if you should be assuming (as it appears you might) that mDumpDictionary is nullptr in FluidMaxWrapper without explicitly initialising it.

~FluidMaxWrapper (which is crashing above) calls object_free on mDumpDictionary. The code of FluidMaxWrapper test mDumpDictionary to see if it is nullptr in a couple of places, but it's not initialised in the constructor - is that a safe assumption?

**Comment by weefuzzy** [comment]
> The code of FluidMaxWrapper test mDumpDictionary to see if it is nullptr in a couple of places, but it's not initialised in the constructor - is that a safe assumption?

It isn't a safe assumption, no 😬  I'll fix it, but on its own topic, unless it seems intimately related to this in some way.

**Comment by tremblap** [comment]
he was looking at me trying to compile - reparing the cmake changes - and he looked inspired so maybe it is linked

**Comment by weefuzzy** [comment]
No, I think these are three separate things

**Comment by AlexHarker** [comment]
The cmake is disconnected. My reason for putting it here is the crash
report above both in terms of trace and what it is telling you (you are
freeing a pointer you didn't allocate....)

**Comment by tremblap** [comment]
as I cannot compile anymore, I cannot tell you. I will see how far back I have to undo the cmake changes to be able to compile, then I'll try to reproduce this bug, and maybe you'll have a fix by then on that other dict issue.

**Comment by tremblap** [comment]
ok I am now back in compile land - I'll try to reproduce the crash by deleting the object as it happened the first time round. If either of you think that fixing the pointer issue is trivial I can try with this too.

**Comment by AlexHarker** [comment]
Fixing the pointer issue (if that is the culprit) is trivial - it just needs setting to nullptr inline or in the constructor.

**Comment by weefuzzy** [comment]
I already have the change locally. Was holding off until JB had finished fixing main 😆

**Comment by tremblap** [comment]
I really cannot reproduce - creating deleting objects with huge memory, running, not running, no luck

**Comment by weefuzzy** [comment]
No worries. The change @AlexHarker pointed to needs making anyway and it's trivial, as he says.

**Comment by AlexHarker** [comment]
I can suggest a non-trivial test for that change to see if it is likely to have an effect in the wild, should that be of interest.

**Comment by weefuzzy** [comment]
By all means. Let's take it off this PR though 😁

**Comment by tremblap** [comment]
send along in an email so I can test and accept this PR after the fact

**Comment by tremblap** [comment]
please, if you can, and it is not too time consumming.

**Comment by tremblap** [comment]
This is working perfectly, merging pre-release

**Pull request merged**
