### PR TITLE
bump Eigen version

### PR DESCRIPTION
**Pull request by weefuzzy**
Bump Eigen version to 3.4

### CODE REVIEW

**Comment by tremblap** [comment]
this is a good moment to test the manual nightly of SC. I'l ltry to find the trigger button

**Comment by weefuzzy** [comment]
you'll be searching a while because I haven't put it on yet! Also, this is on a PR branch: it wouldn't feature in the nightly until being merged...

**Comment by tremblap** [comment]
ok so let's merge then - I cannot test locally without having to download it all which will take ages - if we merge to core we'll see the tests you run there and see if that works, then it'll be fun to see in action in the next nightlies, on which I'll run the UTs and expect a sign error (and will try on all 3 oses - then I'll change the UT to check for absolute value?)

**Comment by weefuzzy** [comment]
The tests have already run on the PR (where it says All Checks Passed).

**Comment by tremblap** [comment]
just got the nightly I was hoping for, will try to run while I do other things

**Comment by tremblap** [comment]
ok as confirmed, the phase of PCA is now inverted. i'll try on Windows and Linux before modding the ut

**Pull request merged**
